name: Build

on: [pull_request, issues]

jobs:
  open-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: open a issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TEST: test

