name: Build

on: [pull_request, issues]

jobs:
  open-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: cheqianh/create-an-issue@e6b4b19
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_WORKFLOW_URL: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
          GITHUB_PR_SHA: ${{ github.event.pull_request.head.sha }}

  ion-test-driver:
    runs-on: macos-10.15
    steps:
      - name: Checkout ion-test-driver
        uses: actions/checkout@master
        with:
          repository: amzn/ion-test-driver
          ref: master
          path: ion-test-driver

      - name: Set up python3 env
        run: python3 -m venv ion-test-driver/venv && . ion-test-driver/venv/bin/activate

      - name: Pip install
        run: pip3 install -r ion-test-driver/requirements.txt && pip3 install -e ion-test-driver

      - name: Run ion-test-driver
        run: python3 ion-test-driver/amazon/iontest/ion_test_driver.py -o output




