name: Build

on: [pull_request, issues]

jobs:
  test:
    runs-on: macos-10.15
    steps:
      - name: test
        run: exit 1

  open-issue:
    runs-on: ubuntu-latest
    needs:
      test
    if: ${{ failures() }}
    steps:
      - uses: actions/checkout@master
      - uses: cheqianh/create-an-issue@e6b4b19
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_WORKFLOW_URL: https://github.com/${{github.repository}}/runs/${{github.run_id}}
          GITHUB_PR_SHA: ${{ github.event.pull_request.head.sha }}
        with:
          assignees: ${{ github.event.sender.login }}


