name: Build

on: [pull_request, issues]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo aaaaaa

  open-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: cheqianh/create-an-issue@e6b4b19
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_WORKFLOW_URL: https://github.com/${{github.repository}}/runs/${{github.run_id}}
          GITHUB_PR_SHA: ${{ github.event.pull_request.head.sha }}
          TEST: ${{github.job}}


