name: Build

on: [pull_request]

jobs:
  test:
    runs-on: macos-10.15
    steps:
      - name: ls
        run: pwd && exit 1

  open-issue:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ failure() }}
    steps:
      - name: get master branch's sha again
        run: echo ${{ github.event.pull_request.base.sha }}

      - name: get master branch's sha again
        run: echo ${{ github.event.pull_request.base.sha }}

      - uses: actions/checkout@master
      - uses: cheqianh/create-an-issue@e6b4b19
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_WORKFLOW_URL: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
          GITHUB_PR_SHA: ${{ github.event.pull_request.head.sha }}
        with:
          assignees: ${{ github.event.sender.login }}

      - name: Checkout ion-test-driver
        uses: actions/checkout@master
        with:
          repository: amzn/ion-test-driver
          ref: master
          path: ion-test-driver

      - name: get master branch's sha again
        run: echo ${{ github.event.pull_request.base.sha }}
