name: ion-test-driver

on: [pull_request]

jobs:
  ion-test-driver:
    runs-on: macos-10.15
    steps:
      - name: Analyze two implementations
        continue-on-error: true
        id: result-diff
        run: exit 1

      - name: Check if ion-test-driver fails
        if: ${{ steps.result-diff.outcome == 'failure' }}
        run: echo 'Implementation behavior changed, Refer to the analysis report in the previous step for the reason.' && exit 1

  open-issue:
    runs-on: ubuntu-latest
    needs: ion-test-driver
    if: ${{ failure() }}
    steps:
      - uses: actions/checkout@master
      - name: open an issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/ion-test-driver-issue.md

