name: Build

on: [pull_request]

jobs:
  test:
    runs-on: macos-10.15
    steps:
      - name: ls
        run: pwd && exit 1

  open-issue:
    runs-on: macos-10.15
    needs: test
    if: ${{ failure() }}
    steps:
      - name: Checkout ion-java
        uses: actions/checkout@master
        with:
          repository: cheqianh/ion-java
          ref: master
          path: ion-java

      - name: pwd
        runs: pwd

      - name: run the other action
        uses: ion-java/.github/workflows