name: Build

on: [pull_request]

jobs:
  test:
    runs-on: macos-10.15
    steps:
      - name: make a file
        run:

  open-issue:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ failure() }}
    steps:
      - uses: actions/checkout@master

      - name: ls
        run: ls

      - name: artifacts
        uses: actions/upload-artifact@v2
        with:
          name: lists_file
          path: ./lists


      - uses: cheqianh/create-an-issue@e6b4b19
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_WORKFLOW_URL: https://github.com/${{github.repository}}/runs/${{github.run_id}}
          GITHUB_PR_SHA: ${{ github.event.pull_request.head.sha }}
        with:
          assignees: ${{ github.event.sender.login }}
