name: Build

on: [pull_request]

jobs:
  test:
    runs-on: macos-10.15
    steps:
      - name: ls
        run: pwd && exit 1

  open-issue:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ failure() }}
    steps:
      - name: get main branch HEAD sha
        run: |
          export sha=aa
          echo "::set-env name=sha::$sha"

      - name: print sha
        run: echo $sha