name: ion-test-driver

on: [pull_request]

jobs:
  ion-test-driver:
    runs-on: macos-10.15
    outputs:
      report: ${{ steps.step1.outputs.test }}
    steps:
      - name: Checkout ion-java
        uses: actions/checkout@master
        with:
          path: ion-java
      - name: Checkout ion-test-driver
        uses: actions/checkout@master
        with:
          repository: cheqianh/ion-java
          ref: action
          path: ion-test-driver

      - name: make dir
        run: mkdir ion-java/.github/actions

      - name: move actions.yml
        run: rm ion-test-driver/amazon/actions/ion-test-driver.yml ion-java/.github/actions

      - name: use local actions
        uses: ./.github/actions